const assert=require('node:assert/strict'),fs=require('node:fs'),W=require('../src/ocr-work.js'),F=require('../src/text-format.js');
const clone=x=>JSON.parse(JSON.stringify(x)),ids=['opaque-a','opaque-b'];
function png(width,height){const header=Buffer.alloc(33);Buffer.from([137,80,78,71,13,10,26,10]).copy(header);header.writeUInt32BE(13,8);header.write('IHDR',12);header.writeUInt32BE(width,16);header.writeUInt32BE(height,20);return 'data:image/png;base64,'+header.toString('base64');}
const token=(id,x)=>({box:{x,y:5,width:20,height:30},id,score:.9,certain:false,manual:false,candidates:[{id,score:.9,nativeScore:.88}]}),result={width:100,height:50,polarity:'dark',threshold:150,lines:[{box:{x:5,y:5,width:85,height:30},tokens:[token(ids[0],5),token(ids[1],35),token(ids[0],65)]}]};
const base={source:{width:120,height:80,name:'synthetic.png',png:png(120,80)},crop:{x:10,y:10,width:100,height:50},result,
 settings:{polarity:'auto',threshold:150,single:false,detail:true,auto:true,join:false,formatEnabled:true,punctuate:false,extraWords:'alpha'},
 view:{selected:{line:0,token:1},reviewOpen:true,pendingOnly:true,segmentationOpen:false},draft:{payload:{text:'a\nb',spans:[{glyph:ids[0],start:0,end:1,text:'a'},{glyph:ids[1],start:2,end:3,text:'b'}]},options:{punctuate:false,extraWords:['alpha']},value:'a b!',dirty:true}};
const original=JSON.stringify(base),text=W.encode(base,ids),saved=W.parse(text,ids);
assert.equal(JSON.stringify(base),original);assert.equal(saved.format,W.FORMAT);assert.equal(saved.source.png,base.source.png);assert.deepEqual(saved.result,result);assert.deepEqual(saved.draft,base.draft);assert(!Object.hasOwn(saved,'mapping'));
const malicious={...clone(base),mapping:{workingMap:{bad:'x'}},writer:{text:'replace'},samples:[{}],translationConsent:true};assert(!W.encode(malicious,ids).includes('workingMap'));
for(const change of [v=>v.source.width++,v=>v.source.png='https://example.com/x.png',v=>v.crop.x=-1,v=>v.result.width++,v=>v.result.lines[0].tokens[0].id='bad',v=>v.result.lines[0].tokens[0].candidates[0].score=2,v=>v.result.lines[0].tokens[0].manual='yes',v=>v.result.lines[0].tokens[0].excludedBoxes=[{x:99,y:0,width:9,height:9}],v=>v.view.selected.token=99,v=>v.settings.extraWords='x'.repeat(3001),v=>v.draft.payload.spans[0].text='bad',v=>v.draft.options.extraWords=['bad<script>']]){const invalid=clone(base);change(invalid);assert.throws(()=>W.encode(invalid,ids));}
assert.throws(()=>W.parse('{',ids),/JSON/);assert.throws(()=>W.parse('x'.repeat(W.MAX_BYTES+1),ids),/7MB/);assert.throws(()=>W.parse(JSON.stringify({...saved,version:99}),ids),/支持/);
const empty=clone(base);empty.result=null;empty.draft=null;empty.view.selected=null;empty.view.reviewOpen=false;assert.equal(W.parse(W.encode(empty,ids),ids).result,null,'unrecognized image can be saved');
const context=W.context(result,{line:0,token:1});assert.deepEqual(context,{box:{x:1,y:1,width:88,height:38},selected:result.lines[0].tokens[1].box,neighbors:2});assert.equal(W.context(result,{line:9,token:0}),null);assert.equal(W.context(result,{line:0,token:0}).neighbors,1);
assert.equal(JSON.stringify(base),original,'context and failed validation preserve input');
const h=W.history({limit:2}),state=n=>({result:{n},selected:{line:0,token:n}});h.record(state(0),state(1),'one');h.record(state(1),state(2),'two');h.record(state(2),state(3),'three');assert.equal(h.state().undo,2);assert.deepEqual(h.undo(),{state:state(2),label:'three'});assert.deepEqual(h.undo(),{state:state(1),label:'two'});assert.equal(h.undo(),null);assert.deepEqual(h.redo(),{state:state(2),label:'two'});
assert.equal(h.record(state(2),{...state(2),selected:null},'selection'),false);assert.equal(h.state().redo,1);h.record(state(2),state(4),'branch');assert.equal(h.state().redo,0);const step=h.undo();step.state.result.n=999;assert.equal(h.redo().state.result.n,4);h.clear();assert.deepEqual(h.state(),{undo:0,redo:0,undoLabel:'',redoLabel:''});
const small=W.history({maxBytes:1});small.record(state(0),state(1),'too large');assert.equal(small.state().undo,0);
const formatter=F.create('the dragon coils falls a b alpha'),draft=F.createDraft(formatter);draft.restore(saved.draft);assert.equal(draft.state().value,'a b!');assert.equal(draft.payload().text,'a b!');const snapshot=draft.snapshot();snapshot.value='bad';assert.equal(draft.state().value,'a b!');draft.update({text:'ab',spans:[]},saved.draft.options);assert(draft.state().stale);assert.equal(draft.state().value,'a b!');draft.update(saved.draft.payload,saved.draft.options);assert(!draft.state().stale);draft.edit('different letters');const bad=draft.snapshot(),restored=F.createDraft(formatter);restored.restore(bad);assert(restored.state().error);restored.restore(null);assert.equal(restored.state(),null);
const source=fs.readFileSync(require.resolve('../src/ocr-work.js'),'utf8');assert(!/\b(fetch|XMLHttpRequest|localStorage|eval)\b/.test(source));
console.log('PASS OCR work/context/history: allowlisted bounded file format, PNG header limits, crop/box/ID/score/span/settings guards, no mapping writes, immutable/atomic parsing; original neighbor geometry, bounded exact undo/redo/branching; edited and invalid drafts round-trip without recognition changes.');
